### ISSUE TITLE
Black textures when updated to latest libraries

### ISSUE THREAD

**Issue by Everade** [Anemolo/GridToFullscreenAnimations#1]
I've been using your effect for quite a while now. Due to security vulnerabilities and just overall for the sake of keeping things up to date, i've updated all libraries to the latest versions. It only required a few small adjustments for three.js and gsap.
gsap v3.12.2, three.js v156.1 and imagesLoaded v5.0.0

However i've ran into an issue where the images are black during the animation. I noticed that this happened after the updated to the latest three.js version.

Here's my report to threejs: https://discourse.threejs.org/t/black-textures-since-r135/55798

Do you have any plans on updating this project?

**Comment by Anemolo** [comment]
Judging by the report and the comments on the related issue. It seems to me that the problem is when getting the naturalwidth/naturalheight of the texture on click. Perhaps with ThreeJS image resize that somehow gets lost or is missing

A possible solution would be to read the image's width/height on `img.onload`, and caching that in the texture set. The image size doesn't change so it would be virtually the same

I don't have any plans on updating the project. But if you submit a PR I can check it out and merge if it looks all good.

**Comment by Everade** [comment]
@Anemolo 
Just opened a pull request.
https://github.com/Anemolo/GridToFullscreenAnimations/pull/2

Note:
I've commented the ".needsUpdate" triggers, because three.js no longer supports resizing of textures if already initialized.

Looking forward to your code review,
thank you.

**Comment by Everade** [comment]
@Anemolo
I was able to fix the black/missing texture bug.
So the pull request is now complete and fully working!
